/* pcl_config.h. Generated by CMake for @PROJECT_NAME@. */

/* PCL version string */
#define PCL_VERSION "1.2.0"

#define HAVE_QHULL 1
#define EIGEN2_SUPPORT

#undef HAVE_OPENNI
#undef HAVE_WXWIDGETS
#undef HAVE_CUDA

