/* pcl_config.h. Generated by CMake for @PROJECT_NAME@. */

/* PCL version string */
#define PCL_VERSION "1.1.0"

#define HAVE_TBB 0

#define HAVE_OPENNI 0

#define HAVE_QHULL 1

#define HAVE_WXWIDGETS 0

#define HAVE_CUDA 0

#ifdef DISABLE_OPENNI
#undef HAVE_OPENNI
#endif

#ifdef DISABLE_QHULL
#undef HAVE_QHULL
#endif

#ifdef DISABLE_WXWIDGETS
#undef HAVE_WXWIDGETS
#endif
