/* pcl_config.h. Generated by CMake for @PROJECT_NAME@. */

/* PCL version string */
#define PCL_VERSION "1.1.0"

#define HAVE_QHULL 1

#ifdef HAVE_OPENNI
#undef HAVE_OPENNI
#endif

#ifdef HAVE_OPENNI
#undef HAVE_OPENNI
#endif

#ifdef HAVE_WXWIDGETS
#undef HAVE_WXWIDGETS
#endif

#ifdef HAVE_CUDA
#undef HAVE_CUDA
#endif

#ifdef DISABLE_OPENNI
#undef HAVE_OPENNI
#endif

#ifdef DISABLE_WXWIDGETS
#undef HAVE_WXWIDGETS
#endif
